[project]
name = "exiainvasion-notebook"
version = "0.1.0"
description = "Python env for fetch_nikke_list.ipynb"
readme = "README.md"
requires-python = ">=3.11"
authors = [{ name = "ExiaInvasion" }]
dependencies = [
  "requests>=2.31",
  "opencc-python-reimplemented>=0.1.7",
  "ipykernel>=6.29"
]
